#! /bin/bash

sudo yum -y install epel-release
sudo yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm

sudo yum -y install --enablerepo=remi,remi-php71 php php-devel php-mbstring php-pdo php-gd php-mysql mariadb mariadb-server libxml2-devel openssl-devel libpng-devel libjpeg-devel bzip2-devel libcurl-devel freetype-devel libmcrypt-devel libxslt-devel php-xml zip unzip git

sudo systemctl enable mariadb.service
sudo systemctl start mariadb.service
sudo systemctl enable httpd.service
sudo systemctl start httpd.service
